import os
from cryptography.hazmat.primitives.asymmetric import x25519
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives import hashes

class ClientKeyPair:
    """
    Container for each machines key pair

    Atributes:
        private_key (x25519.X25519PrivateKey): A private key generated by x25519
        public_key (x25519.X25519PublicKey): A public key generated by x25519
    """
    def __init__(self, private_key: x25519.X25519PrivateKey, public_key: x25519.X25519PublicKey):
        self.private_key = private_key
        self.public_key = public_key

# Ephemeral Key Generation using X25519
def generate_ephemeral_key_pair() -> ClientKeyPair:
    """
    Generate machine key pair
    
    Returns:
        ClientKeyPair: An object containing private and public key
    """
    client_private_key = x25519.X25519PrivateKey.generate()
    client_public_key = client_private_key.public_key()
    return ClientKeyPair(client_private_key, client_public_key)

# Compute Shared Secret 
def compute_shared_secret(private_key: x25519.X25519PrivateKey, peer_public_key: x25519.X25519PublicKey) -> bytes:
    """
    Compute a shared secrect using client private key and peer public key

    Args:
        private_key (x25519.x25519PrivateKey): The client device's private key
        peer_public_key (x25519.x25519PublicKey): The peer devices public key
    
    Returns:
        shared_secret (bytes): Shared secret
    """
    shared_secret = private_key.exchange(peer_public_key)
    return shared_secret

# Derive Symmetric Key using HKDF
def derive_symmetric_key(shared_secret: bytes, info: bytes=b"secure_p2p") -> bytes:
    """
    Use shared secret to derive the keys for encryption

    Args:
        shared_secret (bytes): Shared secret from the key exchange 
        info (bytes): Application specific information

    Returns:
        derived_key (bytes): Key to be used for data encryption
    """
    derived_key = HKDF(
        algorithm=hashes.SHA256(),
        length=32,
        salt=None,
        info=info
    ).derive(shared_secret)
    return derived_key